obj_S = \
 
objs = \
   delay.o \
   lbuf.o \
   run_loop.o \
   vsprintf.o \
   stdio/fcvt.o \
   stdio/printf-stdarg.o \
 
includes += \
-Istdio \
 
 
DEFINS +=
CONFIG_LIB=n
-include $(TOOLS)/rule.mk
 
