obj_S = \
 
objs = \

objs += \
   ble/ble_peripheral_test.o \

INCLUDES += \
-I./
-Iinclude/ \
-Iinclude/common \
-IBaseband/include/ble/$(CHIPID)/ \
-IBaseband/include/common/$(CHIPID)/ \
-IController/include/ \
-IController/include/common/ \
-IController/include/common/$(CHIPID)/ \
-IHost/include/ \
-IHost/include/common/ \
-IProtocol/include/ \
-IProfile/include/ \
 
CC_ARG +=
GEN_LIB=n
include $(MAKE_RULE)
 
